vdbfusion_node:
  ros__parameters:
    use_sim_time: true
    pointcloud_inputs:
      - "/trimesh_self_filter/lidar_front_left"
      - "/trimesh_self_filter/lidar_boom"
    output_topic: "vdbfusion"

    voxel_size: 0.1
    truncation_distance: 2.0
    space_carving: true

    preprocess: true
    apply_pose: true
    min_range: 0.0
    max_range: 3.0

    fill_holes: false
    max_var: 0.0

    timestamp_tolerance_ns: 10000
    static_frame_id: SHOVEL

    publish_interval_ms: 200
    publish_tsdf: true
    publish_mesh: true